#!/usr/bin/env python3
"""Send Intent Blueprint template PDFs via Resend email."""
import os
import sys
import base64
from pathlib import Path

# Try to import resend, install if needed
try:
    import resend
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'resend', '-q'])
    import resend

# Load .env from email directory
script_dir = Path(__file__).parent
env_path = script_dir / '../email/.env'
if env_path.exists():
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                os.environ[key.strip()] = value.strip().strip('"\'')

RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
EMAIL_FROM = os.environ.get('EMAIL_FROM', 'Intent Solutions <noreply@intentsolutions.io>')

if not RESEND_API_KEY:
    print('Error: RESEND_API_KEY not set in tools/email/.env')
    sys.exit(1)

resend.api_key = RESEND_API_KEY

def send_templates(to_email: str):
    zip_path = script_dir / 'intent-blueprint-templates.zip'

    if not zip_path.exists():
        print('Error: ZIP file not found. Run generate-templates.sh first.')
        sys.exit(1)

    with open(zip_path, 'rb') as f:
        zip_content = f.read()

    zip_size_mb = len(zip_content) / 1024 / 1024
    print(f'Sending Intent Blueprint templates to: {to_email}')
    print(f'Attachment: {zip_path} ({zip_size_mb:.2f} MB)')

    try:
        response = resend.Emails.send({
            'from': EMAIL_FROM,
            'to': [to_email],
            'subject': 'Intent Blueprint - 22 Professional Documentation Templates',
            'html': '''
                <h1>Intent Blueprint Templates</h1>
                <p>Attached are 22 professional documentation templates in PDF format.</p>
                <h2>Included Templates:</h2>
                <ol>
                    <li>Product Requirements Document (PRD)</li>
                    <li>Architecture Decision Record (ADR)</li>
                    <li>Task Generation Guide</li>
                    <li>Task Processing Guide</li>
                    <li>Market Research Template</li>
                    <li>Architecture Document</li>
                    <li>Competitor Analysis</li>
                    <li>User Personas</li>
                    <li>User Journeys</li>
                    <li>User Stories</li>
                    <li>Acceptance Criteria</li>
                    <li>QA Gate Document</li>
                    <li>Risk Register</li>
                    <li>Project Brief</li>
                    <li>Brainstorming Template</li>
                    <li>Frontend Specification</li>
                    <li>Test Plan</li>
                    <li>Release Plan</li>
                    <li>Operational Readiness</li>
                    <li>Metrics Dashboard</li>
                    <li>Postmortem Template</li>
                    <li>Playtest/Usability Template</li>
                </ol>
                <p>Generated by <a href="https://github.com/intent-solutions-io/intent-blueprint-docs">Intent Blueprint</a></p>
            ''',
            'attachments': [
                {
                    'filename': 'intent-blueprint-templates.zip',
                    'content': list(zip_content),
                }
            ]
        })

        print('Email sent successfully!')
        print(f'Message ID: {response.get("id", "N/A")}')

    except Exception as e:
        print(f'Error sending email: {e}')
        sys.exit(1)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python send-templates.py <email>')
        print('Example: python send-templates.py jeremy@intentsolutions.io')
        sys.exit(1)

    send_templates(sys.argv[1])
