#!/usr/bin/env npx ts-node
/**
 * Send Intent Blueprint template PDFs via email
 */
import { Resend } from 'resend';
import * as fs from 'fs';
import * as path from 'path';

// Load .env from email directory
const envPath = path.join(__dirname, '../email/.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  envContent.split('\n').forEach(line => {
    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      process.env[key.trim()] = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
    }
  });
}

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const EMAIL_FROM = process.env.EMAIL_FROM || 'Intent Solutions <noreply@intentsolutions.io>';

if (!RESEND_API_KEY) {
  console.error('Error: RESEND_API_KEY not set in tools/email/.env');
  process.exit(1);
}

const resend = new Resend(RESEND_API_KEY);

async function sendTemplates(to: string) {
  const zipPath = path.join(__dirname, 'intent-blueprint-templates.zip');

  if (!fs.existsSync(zipPath)) {
    console.error('Error: ZIP file not found. Run generate-templates.sh first.');
    process.exit(1);
  }

  const zipBuffer = fs.readFileSync(zipPath);
  const zipBase64 = zipBuffer.toString('base64');

  console.log(`Sending Intent Blueprint templates to: ${to}`);
  console.log(`Attachment: ${zipPath} (${(zipBuffer.length / 1024 / 1024).toFixed(2)} MB)`);

  try {
    const { data, error } = await resend.emails.send({
      from: EMAIL_FROM,
      to: [to],
      subject: 'Intent Blueprint - 22 Professional Documentation Templates',
      html: `
        <h1>Intent Blueprint Templates</h1>
        <p>Attached are 22 professional documentation templates in PDF format.</p>
        <h2>Included Templates:</h2>
        <ol>
          <li>Product Requirements Document (PRD)</li>
          <li>Architecture Decision Record (ADR)</li>
          <li>Task Generation Guide</li>
          <li>Task Processing Guide</li>
          <li>Market Research Template</li>
          <li>Architecture Document</li>
          <li>Competitor Analysis</li>
          <li>User Personas</li>
          <li>User Journeys</li>
          <li>User Stories</li>
          <li>Acceptance Criteria</li>
          <li>QA Gate Document</li>
          <li>Risk Register</li>
          <li>Project Brief</li>
          <li>Brainstorming Template</li>
          <li>Frontend Specification</li>
          <li>Test Plan</li>
          <li>Release Plan</li>
          <li>Operational Readiness</li>
          <li>Metrics Dashboard</li>
          <li>Postmortem Template</li>
          <li>Playtest/Usability Template</li>
        </ol>
        <p>Generated by <a href="https://github.com/intent-solutions-io/intent-blueprint-docs">Intent Blueprint</a></p>
      `,
      attachments: [
        {
          filename: 'intent-blueprint-templates.zip',
          content: zipBase64,
        },
      ],
    });

    if (error) {
      console.error('Error sending email:', error);
      process.exit(1);
    }

    console.log('Email sent successfully!');
    console.log('Message ID:', data?.id);
  } catch (err) {
    console.error('Error:', err);
    process.exit(1);
  }
}

// Get email from command line
const email = process.argv[2];
if (!email) {
  console.log('Usage: npx ts-node send-templates.ts <email>');
  console.log('Example: npx ts-node send-templates.ts jeremy@intentsolutions.io');
  process.exit(1);
}

sendTemplates(email);
