import { readdirSync } from 'node:fs';
import { TemplateDefinitionSchema, type TemplateDefinition } from './schema.js';
import { BLUEPRINT_MODULE_BY_ID } from './modules.js';
import { EXAMPLE_PACK_BY_ID } from './examples.js';

type Category = TemplateDefinition['category'];
type Scope = TemplateDefinition['scopes'][number];
type Prefix = TemplateDefinition['recordPrefixes'][number];

const MVP = new Set(['01_prd', '03_generate_tasks', '14_project_brief', '15_brainstorming']);
const STANDARD = new Set([
  ...MVP, '02_adr', '06_architecture', '08_personas', '09_user_journeys',
  '10_user_stories', '11_acceptance_criteria', '17_test_plan', '18_release_plan',
]);

const scopeFor = (id: string): Scope[] => [
  ...(MVP.has(id) ? ['mvp' as const] : []),
  ...(STANDARD.has(id) ? ['standard' as const] : []),
  'comprehensive' as const,
];

const section = (id: string, title: string, purpose: string, module?: string) => ({
  id, title, purpose, required: true, ...(module ? { module } : {}),
});

interface DefinitionInput {
  id: string;
  type: string;
  name: string;
  category: Category;
  purpose: string;
  prefixes: Prefix[];
  modules: string[];
  examples?: string[];
  standards?: string[];
  sections: Array<ReturnType<typeof section>>;
}

const define = (input: DefinitionInput): TemplateDefinition => TemplateDefinitionSchema.parse({
  id: input.id,
  documentType: input.type,
  name: input.name,
  filename: `${input.id}.md`,
  version: '3.0.0',
  category: input.category,
  description: input.purpose,
  purpose: input.purpose,
  scopes: scopeFor(input.id),
  recordPrefixes: input.prefixes,
  sections: input.sections,
  modules: input.modules,
  examplePacks: input.examples || [],
  standardsAlignment: input.standards || [],
});

export const TEMPLATE_DEFINITIONS: readonly TemplateDefinition[] = [
  define({ id: '01_prd', type: 'prd', name: 'Product Requirements Document', category: 'Product & Strategy', purpose: 'Define the problem, scope, objectives, and verifiable requirements.', prefixes: ['OBJ', 'REQ', 'RISK', 'CTRL'], modules: ['requirements', 'risk-controls', 'control-evidence', 'metrics', 'safety-applicability', 'governance', 'traceability'], standards: ['ISO/IEC/IEEE 29148:2018'], sections: [section('context', 'Context and evidence', 'Record the problem and source basis.', 'requirements'), section('objectives', 'Objectives and users', 'Define outcomes, users, and stakeholders.'), section('scope', 'Scope and applicability', 'Set boundaries, constraints, and exclusions.'), section('requirements', 'Requirements registry', 'Record stable, verifiable requirements.', 'requirements'), section('risks', 'Risks and safeguards', 'Link risks, controls, and applicability.', 'risk-controls'), section('verification', 'Verification and governance', 'Define evidence, measures, review, and change.', 'governance')] }),
  define({ id: '02_adr', type: 'architecture-decision-record', name: 'Architecture Decision Record', category: 'Technical Architecture', purpose: 'Record an evidence-backed technical decision and its lifecycle.', prefixes: ['ADR', 'REQ', 'RISK', 'TASK', 'TEST'], modules: ['evidence-register', 'risk-controls', 'governance', 'traceability'], examples: ['adr-evaluation-methods'], standards: ['ISO/IEC/IEEE 42010:2022'], sections: [section('status', 'Status and ownership', 'Name the decision owner and review state.', 'governance'), section('context', 'Context and decision drivers', 'Link requirements, constraints, and evidence.', 'evidence-register'), section('alternatives', 'Alternatives and evaluation', 'Compare options without a preselected winner.'), section('decision', 'Decision and rationale', 'Record the chosen option and reasoning.'), section('consequences', 'Consequences and risks', 'Record tradeoffs and risk treatment.', 'risk-controls'), section('validation', 'Implementation and validation', 'Link tasks, tests, revisit triggers, and supersession.', 'traceability')] }),
  define({ id: '03_generate_tasks', type: 'task-plan', name: 'Task Generation', category: 'Development Workflow', purpose: 'Derive executable work without assuming a stack, team, or estimate.', prefixes: ['TASK', 'REQ', 'STORY', 'AC', 'TEST', 'RISK'], modules: ['requirements', 'risk-controls', 'actions', 'traceability'], examples: ['task-breakdown-patterns'], sections: [section('inputs', 'Input set', 'List requirements, decisions, and evidence.'), section('method', 'Decomposition method', 'Explain how work is split.'), section('tasks', 'Task registry', 'Record work, owner, state, and evidence.', 'actions'), section('dependencies', 'Dependencies and blockers', 'Record ordering and blocked state.'), section('estimates', 'Estimate method and confidence', 'Keep estimates sourced or assumed.'), section('traceability', 'Delivery traceability', 'Link requirements, criteria, tasks, and tests.', 'traceability')] }),
  define({ id: '04_process_task_list', type: 'delivery-workflow', name: 'Task Processing', category: 'Development Workflow', purpose: 'Govern execution under an explicitly selected delivery method.', prefixes: ['TASK', 'ACT', 'RISK', 'CTRL'], modules: ['actions', 'control-evidence', 'governance', 'traceability'], examples: ['agile-kanban-workflows'], sections: [section('method', 'Method and applicability', 'Select the workflow and explain fit.'), section('policy', 'Ready and done policy', 'Define entry and completion evidence.'), section('ledger', 'Work ledger', 'Track state, dependencies, and ownership.', 'actions'), section('blockers', 'Blockers and escalation', 'Record blocked-since and next review.'), section('waivers', 'Decisions and waivers', 'Record evidence, expiry, and authority.', 'control-evidence'), section('improvement', 'Flow review and actions', 'Capture validated improvements.')] }),
  define({ id: '05_market_research', type: 'market-research', name: 'Market Research', category: 'Product & Strategy', purpose: 'Separate a research plan from dated, sourced findings.', prefixes: ['OBJ', 'RISK'], modules: ['research-evidence', 'metrics', 'risk-controls', 'evidence-register'], examples: ['research-instruments'], sections: [section('questions', 'Questions and scope', 'Define what will be researched.'), section('protocol', 'Protocol and method', 'Record method, sampling, and limitations.', 'research-evidence'), section('sources', 'Source register', 'Capture dated sources and provenance.', 'evidence-register'), section('findings', 'Findings and confidence', 'Separate facts, estimates, inferences, and unknowns.'), section('opportunity', 'Opportunity and risk', 'Record implications without fabricated market figures.', 'risk-controls'), section('refresh', 'Recommendations and refresh', 'Name decisions, owners, and update cadence.')] }),
  define({ id: '06_architecture', type: 'architecture-description', name: 'Architecture Description', category: 'Technical Architecture', purpose: 'Describe a system from verified constraints and stakeholder viewpoints.', prefixes: ['REQ', 'ADR', 'RISK', 'CTRL', 'TEST'], modules: ['requirements', 'safety-applicability', 'risk-controls', 'operations', 'governance', 'traceability'], examples: ['architecture-model-patterns'], standards: ['ISO/IEC/IEEE 42010:2022', 'C4 model'], sections: [section('stakeholders', 'Stakeholders and concerns', 'Identify the system of interest and decision concerns.'), section('constraints', 'Requirements and constraints', 'Link verified drivers.', 'requirements'), section('views', 'Viewpoints and models', 'Describe only justified views and textual alternatives.'), section('system', 'Components, interfaces, and flows', 'Record responsibilities without a preset stack.'), section('safety', 'Trust boundaries and failure modes', 'Cover security, privacy, accessibility, and resilience.', 'safety-applicability'), section('evolution', 'Decisions, validation, and evolution', 'Link ADRs, tests, operations, and review.', 'traceability')] }),
  define({ id: '07_competitor_analysis', type: 'competitor-analysis', name: 'Competitor Analysis', category: 'Product & Strategy', purpose: 'Produce comparable, dated competitive evidence without invented claims.', prefixes: ['OBJ', 'RISK'], modules: ['research-evidence', 'metrics', 'risk-controls', 'evidence-register'], examples: ['competitive-research-methods'], sections: [section('boundary', 'Questions and category boundary', 'Define inclusion and comparison rules.'), section('protocol', 'Collection protocol', 'Record legal, ethical, and dated methods.', 'research-evidence'), section('sources', 'Source register', 'Capture provenance and confidence.', 'evidence-register'), section('profiles', 'Comparable profiles', 'Leave unknown cells explicit.'), section('comparison', 'Normalized comparison', 'Label fact, estimate, and inference.'), section('monitoring', 'Implications and monitoring', 'Record risks, decisions, and refresh cadence.', 'risk-controls')] }),
  define({ id: '08_personas', type: 'personas', name: 'Evidence-Based Personas', category: 'Product & Strategy', purpose: 'Derive user representations from research without fictional completed people.', prefixes: ['OBJ', 'REQ', 'STORY'], modules: ['research-evidence', 'safety-applicability', 'requirements', 'traceability'], examples: ['persona-research-instruments'], sections: [section('basis', 'Research basis', 'Record sources, sample, and segmentation method.', 'research-evidence'), section('records', 'Persona records', 'Describe goals, jobs, contexts, and constraints.'), section('accessibility', 'Accessibility, privacy, and bias review', 'Protect people and identify accommodation needs.', 'safety-applicability'), section('confidence', 'Evidence and confidence', 'Expose conflicts, assumptions, and unknowns.'), section('implications', 'Product implications', 'Link personas to requirements and stories.', 'traceability'), section('invalidation', 'Review and invalidation triggers', 'Define when a persona must change.')] }),
  define({ id: '09_user_journeys', type: 'user-journeys', name: 'User Journeys', category: 'User Experience', purpose: 'Model a sourced user path including failure and recovery.', prefixes: ['REQ', 'STORY', 'RISK'], modules: ['research-evidence', 'safety-applicability', 'metrics', 'traceability'], examples: ['journey-notation-patterns'], sections: [section('scope', 'Persona, use case, and outcome', 'Set evidence-backed journey boundaries.'), section('stages', 'Stages and touchpoints', 'Record needs, evidence, and owners.'), section('data', 'Data and privacy touchpoints', 'Identify consent and sensitive flows.', 'safety-applicability'), section('recovery', 'Failure and recovery paths', 'Cover errors and assistive-technology paths.'), section('measures', 'Measures and unknowns', 'Define sourced metrics and gaps.', 'metrics'), section('links', 'Requirement and story links', 'Connect the journey to delivery.', 'traceability')] }),
  define({ id: '10_user_stories', type: 'user-stories', name: 'User Stories', category: 'User Experience', purpose: 'Maintain a traceable, prioritized backlog derived from evidence.', prefixes: ['STORY', 'REQ', 'AC', 'TEST', 'RISK'], modules: ['requirements', 'risk-controls', 'traceability', 'governance'], examples: ['story-pattern-library'], sections: [section('scope', 'Backlog scope', 'Name the decision and source boundary.'), section('stories', 'Story registry', 'Record user, need, value, owner, and state.'), section('quality', 'NFR, risk, and control links', 'Connect cross-cutting needs.', 'risk-controls'), section('acceptance', 'Acceptance and test links', 'Map each story to observable evidence.', 'traceability'), section('dependencies', 'Dependencies and priority', 'Record rationale and blocked state.'), section('review', 'Review and maintenance', 'Set ownership and refresh triggers.', 'governance')] }),
  define({ id: '11_acceptance_criteria', type: 'acceptance-criteria', name: 'Acceptance Criteria', category: 'User Experience', purpose: 'Define observable acceptance conditions and safe reusable patterns.', prefixes: ['AC', 'REQ', 'STORY', 'TEST', 'CTRL'], modules: ['requirements', 'control-evidence', 'safety-applicability', 'traceability'], examples: ['acceptance-pattern-library'], sections: [section('applicability', 'Applicability', 'Define the requirement and context.'), section('criteria', 'Criterion registry', 'Record precondition, action, and observable outcome.'), section('negative', 'Negative, edge, and abuse cases', 'Cover failure behavior and misuse.'), section('safety', 'Security, privacy, and accessibility', 'Apply relevant safeguards.', 'safety-applicability'), section('evidence', 'Verification evidence', 'Define how each criterion is proven.'), section('links', 'Requirement, story, and test links', 'Validate traceability.', 'traceability')] }),
  define({ id: '12_qa_gate', type: 'qa-gate-decision', name: 'QA Gate Decision', category: 'Quality Assurance', purpose: 'Produce an auditable pass, fail, or restricted-release decision.', prefixes: ['CTRL', 'TEST', 'REL', 'RISK', 'ADR'], modules: ['control-evidence', 'governance', 'risk-controls', 'traceability'], examples: ['ci-tooling-examples'], sections: [section('scope', 'Gate scope', 'Name release, controls, and evidence boundary.'), section('controls', 'Gate and control registry', 'Identify non-waivable and conditional controls.', 'control-evidence'), section('evidence', 'Evidence and roles', 'Record separation of duties and proof.'), section('decision', 'Decision rules and result', 'Record a reviewable outcome.', 'governance'), section('waivers', 'Waivers and compensation', 'Require authority, reason, evidence, and expiry.'), section('failure', 'Failure and rollback', 'Define escalation and rollback triggers.', 'risk-controls')] }),
  define({ id: '13_risk_register', type: 'risk-register', name: 'Risk Register', category: 'Development Workflow', purpose: 'Govern risk exposure, treatment, monitoring, and acceptance.', prefixes: ['RISK', 'CTRL', 'REQ', 'ACT'], modules: ['risk-controls', 'control-evidence', 'actions', 'governance', 'traceability'], examples: ['risk-scoring-methods'], standards: ['ISO 31000', 'NIST CSF 2.0'], sections: [section('method', 'Method and appetite', 'Define applicability, tolerance, and scoring method.'), section('risks', 'Risk registry', 'Record cause, event, consequence, owner, and state.', 'risk-controls'), section('controls', 'Controls and evidence', 'Record current controls and proof.', 'control-evidence'), section('residual', 'Residual exposure and treatment', 'Compare exposure to appetite.'), section('monitoring', 'Triggers and review', 'Set indicators and review dates.'), section('acceptance', 'Acceptance and related records', 'Name authority and lifecycle links.', 'traceability')] }),
  define({ id: '14_project_brief', type: 'project-brief', name: 'Project Brief', category: 'Product & Strategy', purpose: 'Support an explicit investment or initiation decision.', prefixes: ['OBJ', 'REQ', 'RISK', 'ADR'], modules: ['evidence-register', 'metrics', 'risk-controls', 'governance', 'traceability'], sections: [section('context', 'Problem and context', 'Record the evidence-backed opportunity.', 'evidence-register'), section('options', 'Options and decision status', 'Compare credible choices.'), section('objectives', 'Objectives, outcomes, and scope', 'Define boundaries and measures.', 'metrics'), section('case', 'Benefits, costs, and confidence', 'Label estimates and their method.'), section('governance', 'Stakeholders and governance', 'Name decision ownership.', 'governance'), section('decision', 'Risks and requested decision', 'Surface dependencies, assumptions, and authority.', 'risk-controls')] }),
  define({ id: '15_brainstorming', type: 'brainstorming-record', name: 'Brainstorming Record', category: 'Development Workflow', purpose: 'Preserve ideas and evidence without promoting them to project facts.', prefixes: ['OBJ', 'RISK', 'ADR', 'ACT'], modules: ['evidence-register', 'safety-applicability', 'risk-controls', 'actions', 'governance'], examples: ['facilitation-methods'], sections: [section('purpose', 'Purpose and evidence', 'Name the problem and constraints.', 'evidence-register'), section('participation', 'Participation and dissent', 'Record contributors and contrary views.'), section('ideas', 'Idea register', 'Preserve raw ideas and provenance.'), section('hypotheses', 'Hypotheses and falsification', 'Define how ideas could be disproven.'), section('impact', 'Safety and accessibility impacts', 'Evaluate affected people.', 'safety-applicability'), section('disposition', 'Disposition and actions', 'Record rationale, experiments, and owners.', 'actions')] }),
  define({ id: '16_frontend_spec', type: 'frontend-specification', name: 'Frontend Specification', category: 'Technical Architecture', purpose: 'Define a stack-neutral user-interface implementation contract.', prefixes: ['REQ', 'ADR', 'CTRL', 'RISK', 'TEST', 'TASK'], modules: ['requirements', 'safety-applicability', 'control-evidence', 'traceability'], examples: ['react-frontend'], sections: [section('context', 'Product and UX context', 'Link designs, requirements, and users.'), section('support', 'Platforms and support', 'Record applicability and sourced constraints.'), section('components', 'Components and states', 'Cover normal, empty, error, loading, and offline states.'), section('data', 'Data, security, and privacy', 'Record flows and controls.', 'safety-applicability'), section('accessibility', 'Accessibility and localization', 'Cover semantics, motion, language, and assistive use.'), section('delivery', 'Performance, tests, and ownership', 'Link components, requirements, tests, and tasks.', 'traceability')] }),
  define({ id: '17_test_plan', type: 'test-plan', name: 'Test Plan', category: 'Quality Assurance', purpose: 'Define a justified verification strategy and its evidence.', prefixes: ['TEST', 'REQ', 'RISK', 'CTRL', 'REL'], modules: ['requirements', 'risk-controls', 'control-evidence', 'safety-applicability', 'traceability'], examples: ['test-tooling'], standards: ['ISO/IEC/IEEE 29119 series'], sections: [section('scope', 'Scope and objectives', 'Name test basis and exclusions.'), section('strategy', 'Strategy and allocation rationale', 'Derive coverage from risk, not a fixed pyramid.'), section('tests', 'Test registry', 'Record IDs, environments, data, and expected evidence.'), section('coverage', 'Safety and quality coverage', 'Cover applicable security, privacy, accessibility, and resilience.', 'safety-applicability'), section('criteria', 'Entry, exit, and suspension criteria', 'Define decision boundaries.'), section('evidence', 'Execution, defects, and approval', 'Link actual results and release evidence.', 'traceability')] }),
  define({ id: '18_release_plan', type: 'release-plan', name: 'Release Plan', category: 'Quality Assurance', purpose: 'Authorize a reproducible and reversible release.', prefixes: ['REL', 'CTRL', 'TEST', 'RISK', 'ADR', 'ACT'], modules: ['control-evidence', 'operations', 'risk-controls', 'governance', 'actions', 'traceability'], examples: ['deployment-provider-examples'], standards: ['SLSA 1.2'], sections: [section('identity', 'Release identity and scope', 'Name artifact, source revision, and owner.'), section('provenance', 'Artifacts and provenance', 'Record digests, SBOM, builder, inputs, and signature.'), section('strategy', 'Strategy and environments', 'Select a deployment approach without vendor defaults.'), section('migration', 'Migration and reversibility', 'Prove backup, rollback, and data safety.'), section('evidence', 'Quality evidence and approval', 'Link tests, controls, risks, and accountable approval.', 'traceability'), section('operations', 'Rollout, monitoring, and rollback', 'Define triggers, evidence, communication, and post-release checks.', 'operations')] }),
  define({ id: '19_operational_readiness', type: 'operational-readiness', name: 'Operational Readiness', category: 'Technical Architecture', purpose: 'Support an evidence-backed go-live decision.', prefixes: ['CTRL', 'RISK', 'TEST', 'REL', 'INC', 'ACT'], modules: ['operations', 'control-evidence', 'safety-applicability', 'risk-controls', 'governance', 'traceability'], examples: ['cloud-kubernetes-operations'], sections: [section('services', 'Services and owners', 'Record applicability and dependencies.', 'operations'), section('objectives', 'SLO, capacity, and observability', 'Derive operational targets from evidence.'), section('response', 'Incident and runbook readiness', 'Record escalation, recovery, and ownership.'), section('recovery', 'Backup and recovery evidence', 'Link actual exercise evidence.'), section('controls', 'Security, privacy, and gaps', 'Record controls, waivers, and risk.', 'control-evidence'), section('decision', 'Go-live decision', 'Name conditions, evidence, and approval.', 'governance')] }),
  define({ id: '20_metrics_dashboard', type: 'metrics-registry', name: 'Metrics Registry and Dashboard', category: 'Development Workflow', purpose: 'Define trustworthy measures before choosing a presentation.', prefixes: ['OBJ', 'REQ', 'CTRL', 'METRIC', 'ACT'], modules: ['metrics', 'evidence-register', 'safety-applicability', 'actions', 'traceability'], examples: ['dashboard-implementation-examples'], sections: [section('questions', 'Objectives and questions', 'Define the decisions metrics support.'), section('registry', 'Metric registry', 'Record formula, unit, grain, dimensions, and owner.', 'metrics'), section('lineage', 'Sources, lineage, and freshness', 'Record provenance and quality.', 'evidence-register'), section('targets', 'Baselines, targets, and rationale', 'Label every threshold state.'), section('privacy', 'Privacy and access', 'Control sensitive measures.', 'safety-applicability'), section('actions', 'Alerts, actions, and views', 'Link measures to accountable decisions.', 'actions')] }),
  define({ id: '21_postmortem', type: 'postmortem', name: 'Postmortem', category: 'Quality Assurance', purpose: 'Create an evidence-based incident learning and action record.', prefixes: ['INC', 'ACT', 'RISK', 'CTRL', 'TEST'], modules: ['operations', 'control-evidence', 'risk-controls', 'actions', 'governance', 'traceability'], examples: ['causal-analysis-methods'], standards: ['NIST SP 800-61 Rev. 3'], sections: [section('incident', 'Incident and impact', 'Record classification, scope, and evidence.'), section('timeline', 'Evidence timeline', 'Use immutable UTC event references.'), section('analysis', 'Causal and contributing analysis', 'Remain blameless and evidence-led.'), section('response', 'Detection, response, and recovery', 'Record what helped, hurt, and was lucky.', 'operations'), section('actions', 'Actions and verification', 'Name owners, due dates, and closure proof.', 'actions'), section('closure', 'Closure and recurrence monitoring', 'Link controls, risks, communication, and review.', 'governance')] }),
  define({ id: '22_playtest_usability', type: 'usability-study', name: 'Usability Study', category: 'Quality Assurance', purpose: 'Separate a usability study plan, report, and optional instruments.', prefixes: ['OBJ', 'REQ', 'STORY', 'TEST', 'RISK', 'ACT'], modules: ['research-evidence', 'safety-applicability', 'metrics', 'actions', 'traceability'], examples: ['usability-instruments'], sections: [section('status', 'Study type and status', 'Distinguish plan from completed report.'), section('protocol', 'Objectives, protocol, and tasks', 'Record hypothesis and method.', 'research-evidence'), section('participants', 'Sampling, consent, and privacy', 'Record rationale, bias, retention, and withdrawal.', 'safety-applicability'), section('execution', 'Execution and deviations', 'Record what actually happened.'), section('findings', 'Findings and limitations', 'Link raw evidence, confidence, and unknowns.', 'metrics'), section('actions', 'Recommendations and traceability', 'Link requirements, stories, risks, and accountable actions.', 'traceability')] }),
];

export const TEMPLATE_BY_ID = new Map(TEMPLATE_DEFINITIONS.map(definition => [definition.id, definition]));

export const LEGACY_TEMPLATE_MIGRATIONS = TEMPLATE_DEFINITIONS.map(definition => ({
  legacyId: definition.id,
  legacyFilename: definition.filename,
  currentId: definition.id,
  currentVersion: definition.version,
  status: 'schema-default-legacy-opt-in' as const,
}));

export function validateTemplateCatalog(templatesDir: string): void {
  const ids = TEMPLATE_DEFINITIONS.map(definition => definition.id);
  const filenames = TEMPLATE_DEFINITIONS.map(definition => definition.filename);
  if (new Set(ids).size !== ids.length || new Set(filenames).size !== filenames.length) {
    throw new Error('Template catalog IDs and filenames must be unique');
  }
  for (const definition of TEMPLATE_DEFINITIONS) {
    TemplateDefinitionSchema.parse(definition);
    if (definition.filename !== `${definition.id}.md`) {
      throw new Error(`Template filename does not match ID: ${definition.id}`);
    }
    for (const moduleId of definition.modules) {
      if (!BLUEPRINT_MODULE_BY_ID.has(moduleId)) {
        throw new Error(`Template ${definition.id} references unknown module: ${moduleId}`);
      }
    }
    for (const exampleId of definition.examplePacks) {
      if (!EXAMPLE_PACK_BY_ID.has(exampleId)) {
        throw new Error(`Template ${definition.id} references unknown example pack: ${exampleId}`);
      }
    }
  }
  const files = readdirSync(templatesDir).filter(file => file.endsWith('.md')).sort();
  const expected = [...filenames].sort();
  if (JSON.stringify(files) !== JSON.stringify(expected)) {
    throw new Error('Canonical template files do not match the typed 22-entry catalog');
  }
}
